### PR TITLE
Adds Pandas DF JSON materializer

### PR DESCRIPTION
**Pull request by bryangalindo**
This change adds the PandasJsonWriter `to_json` function to the existing Pandas materializer example script and updates the materialization notebook.

## Changes
- examples/pandas/materialization/notebook.ipynb
- examples/pandas/materialization/my_script.py

## How I tested this
- Successfully ran unit tests for py3.11 locally using the following command in the root directory: `pytest tests/`
- Successfully ran unit tests for py3.7-3.10 using docker run command found [here](https://github.com/DAGWorks-Inc/hamilton/blob/main/developer_setup.md#running-tests-in-docker).

## Notes
N/A

## Checklist
- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [x] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Review by skrawcz — COMMENTED** [review]
The image in the notebook doesn't reflect what should be visualized. Otherwise the code looks great, thanks!

**Comment by bryangalindo** [comment]
> The image in the notebook doesn't reflect what should be visualized. Otherwise the code looks great, thanks!

What needs to be corrected about the image below? 

-  a) Should there be two separate pictures, one for each materializer?
-  b) Should there be one single picture, but two sets of independent DAG graphs for each materializer?
-  c) or something else?

image

**Comment by skrawcz** [comment]
> > The image in the notebook doesn't reflect what should be visualized. Otherwise the code looks great, thanks!
> 
> What needs to be corrected about the image below?
> 
> * a) Should there be two separate pictures, one for each materializer?
> * b) Should there be one single picture, but two sets of independent DAG graphs for each materializer?
> * c) or something else?
> 
> image

this image looks correct now! I was meaning in the notebook the image isn't this one.

**Comment by bryangalindo** [comment]
> > > The image in the notebook doesn't reflect what should be visualized. Otherwise the code looks great, thanks!
> > 
> > 
> > What needs to be corrected about the image below?
> > 
> > * a) Should there be two separate pictures, one for each materializer?
> > * b) Should there be one single picture, but two sets of independent DAG graphs for each materializer?
> > * c) or something else?
> > 
> > image
> 
> This image looks correct! I was meaning in the notebook the image isn't this one.
> 
> The one in the notebook that's checked in looks like:
> 
> Screen Shot 2023-09-14 at 10 27 32 PM

I think this was an issue with my PyCharm IDE's Jupyter Notebook integration. I updated my PyCharm and ran all the cells, so the checked-in notebook visualization should be updated.

**Review by skrawcz — APPROVED** [review]
:shipit:

**Pull request merged**
