### PR TITLE
Add pyspark & ibis capture to SDK

### PR DESCRIPTION
**Pull request by skrawcz**
adds sdk capture of some basic ibis and pyspark info.

## Changes
- sdk

## How I tested this
- locally

## Notes
- need to create tests

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by zilto** [comment]
Ibis 9.0 added a `.describe()` method (equivalent to `pd.DataFrame().describe()`)

**Comment by skrawcz** [comment]
yeah but I don't want it to cause a materialization -- since ibis is lazy,
right?

**Comment by skrawcz** [comment]
Just need to add some tests.

**Comment by skrawcz** [comment]
closing in support of #895

**Pull request closed without merging**
