### PR TITLE
Add e2e tests for async pipe_family

### PR DESCRIPTION
**Pull request by jernejfrank**
Addtion to #1223 -- Converted the initial test script to integration tests.

### CODE REVIEW

**Review by elijahbenizzy — APPROVED** [review]
Thank you!

**Review by elijahbenizzy — APPROVED** [review]
Looks good! We're fixing the tests shortly -- they're failing due to stuff entirely unrelated to your change, we think. Then mind rebasing against main and pushing to the branch (we can double-check that they all pass)?

**Comment by jernejfrank** [comment]
> Looks good! We're fixing the tests shortly -- they're failing due to stuff entirely unrelated to your change, we think. Then mind rebasing against main and pushing to the branch (we can double-check that they all pass)?

Sounds good -- FWIW locally the tests were passing.

**Comment by skrawcz** [comment]
> > Looks good! We're fixing the tests shortly -- they're failing due to stuff entirely unrelated to your change, we think. Then mind rebasing against main and pushing to the branch (we can double-check that they all pass)?
> 
> Sounds good -- FWIW locally the tests were passing.

you should be good to rebase now.

**Pull request merged**
