### PR TITLE
Adding initial commit for Pandas Stata Read and Write 

### PR DESCRIPTION
**Pull request by JoJo10Smith**
This PR is in response to Issue #377 where I will be adding a PandasStataReader and PandasStataWriter function

`read_stata`: https://pandas.pydata.org/docs/reference/api/pandas.read_stata.html
`to_stata`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_stata.html

## Changes

`pandas_extensions.py:` Added the functions to read and write Stata files (DTA file extension)
`my_script.py`: Added the example of Stata materialization and optional to add Hamilton to PATH with directory
`notebook.ipynb`: Added the example of Stata materialization and optional to add Hamilton to PATH with directory
`test_pandas_extensions.py`: Added test cases for the read_stata and to_stata functions that are called PandasStataReader and PandasStataWriter respectively
`test_load_from_data.dta:` A simple Stata file (DTA file extension) with example data to test functionality

## How I tested this

My final commit passed all the checks in the pre-commit module as well as passing all the CircleCi tests.

image

## Notes
The new Dag looks as follows: 

image

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [x] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by JoJo10Smith** [comment]
@skrawcz this PR is ready for review.

Thanks
Jordan

**Review by skrawcz — APPROVED** [review]
Looks good. Thanks @JoJo10Smith .

Do you want to help me write the commit message? That is, do a rebase and squash all the commits and provide a tidy commit message?

**Comment by skrawcz** [comment]
(you have to rebase this branch because of your notebook fix)

**Comment by JoJo10Smith** [comment]
**Please do not merge, I need to confirm that ll previous changes are still there.**

**Pull request merged**
