### PR TITLE
ISSUE-75: Update build script to enable docker container contain all environments for all examples.

### LINKED ISSUE #75: Make docker container contain all environments for all examples
**Is your feature request related to a problem? Please describe.**
The docker container created for the examples does not enable one to run all the examples. The script to build environments that is used in the build process, excludes building environments for examples that have multiple requirements files, e.g.`requirements-ray.txt` is required to run `run_ray.py` in the data_quality example. This means that people can only run one variant in these examples.

**Describe the solution you'd like**
The build script should prepare all the environments in an example.
E.g. 

 - `requirements.txt` would map to `hamilton-env`
 - `requirements-ray.txt` would map to `hamilton-env-ray` 
 - `requirements-dask.txt` would map to `hamilton-env-dask`

**Describe alternatives you've considered**
No doing this. Leaving things as is.

**Additional context**
Script in question:
https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/make_python_virtualenv.sh 

It is used here:
https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/Dockerfile

### PR DESCRIPTION
**Pull request by CharityKithaka**
[Closes #75 : Modify the build script to facilitate the building of all environments based on the extensions on the requirements files on all modules.]

## Checklist

- [X] PR has an informative and human-readable title (this will be pulled into the release notes)
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by CharityKithaka** [comment]
Hey @skrawcz kindly find above.

**Review by skrawcz — CHANGES_REQUESTED** [review]
Thanks for the PR! 

I think I might have not explained the desired end state correctly. The ideal end state is that, for each example directory, there's a virtual environment corresponding to each requirements*.txt file. 

From what I can tell, this does install all requirements*.txt files, however it installs all of them into the same virtual environment for an example. 

Here's some pseudo code that is close to your code now, but adjust things slightly.

find all folders with requirements files
For each folder
   for each requirements file 
       determine whether file has suffix or not (e.g. ray, dask, or none)
       remove & create new environment with suffix
       activate the environment
       install that requirements file
       deactivate

Shouldn't be much to change what you have to reflect the above. Let me know if you have questions or need clarification.

**Comment by CharityKithaka** [comment]
Hey, @skrawcz wanted to confirm if this issue was closed.

Charity.

**Comment by skrawcz** [comment]
> Hey, @skrawcz wanted to confirm if this issue was closed or if its something that's still pending.🙂
> 
> Charity.

@CharityKithaka no this is still open!

**Comment by skrawcz** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
