### PR TITLE
🚧 Adds MLflow materializer

### PR DESCRIPTION
**Pull request by bryangalindo**
🚧 WIP 🚧 

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by bryangalindo** [comment]
how to save a model into mlflow: https://mlflow.org/docs/latest/quickstart.html#store-a-model-in-mlflow
how to load a model from mlflow: https://mlflow.org/docs/latest/quickstart.html#load-a-model-from-a-specific-training-run-for-inference

**Comment by bryangalindo** [comment]
most (if not all) model flavors 
```py
>>> import mlflow
>>> mlflow.__version__
'2.7.1'
>>> [attr for attr in dir(mlflow) if hasattr(getattr(mlflow, attr), 'log_model')]
[
    'catboost', 'diviner', 'fastai', 'gluon', 'h2o', 'johnsnowlabs', 'langchain', 
    'lightgbm', 'mleap', 'onnx', 'openai', 'paddle', 'pmdarima', 'prophet', 
    'pyfunc', 'pytorch', 'sentence_transformers', 'sklearn', 'spacy', 'spark', 
    'statsmodels', 'tensorflow', 'transformers', 'xgboost'
]
```

**Comment by bryangalindo** [comment]
example of load/save flow for sklearn model flavor:
```py
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

import mlflow
from mlflow.models import infer_signature

run_id = None

db = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

with mlflow.start_run() as run:
    rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
    rf.fit(X_train, y_train)
    save_predictions = rf.predict(X_test)
    signature = infer_signature(X_test, save_predictions)
    mlflow.sklearn.log_model(rf, "model", signature=signature)
    run_id = run.info.run_id

model = mlflow.sklearn.load_model(f"runs:/{run_id}")
load_predictions = model.predict(X_test)

assert save_predictions == load_predictions
```

**disclaimer**: I have not tested this

**Comment by bryangalindo** [comment]
chatgpt-generated tensorflow example:
```py
import tensorflow as tf

import mlflow
from mlflow.models import infer_signature

run_id = None
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.boston_housing.load_data()

with mlflow.start_run() as run:
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=2)
    save_predictions = model.predict(X_test)
    signature = infer_signature(X_test, save_predictions)
    mlflow.tensorflow.log_model(tf_saved_model_dir="model", tf_model=model, signature=signature)
    run_id = run.info.run_id

loaded_model = mlflow.tensorflow.load_model(model_uri=f"runs:/{run_id}")
load_predictions = loaded_model.predict(X_test)

assert save_predictions == load_predictions
```
**disclaimer**: I have not tested this

**Comment by bryangalindo** [comment]
Experimental flavors, so can we probably prioritize these last?
- [Diviner (diviner)](https://mlflow.org/docs/latest/models.html#diviner-diviner)
- [John Snow Labs (johnsnowlabs) (Experimental)](https://mlflow.org/docs/latest/models.html#john-snow-labs-johnsnowlabs-experimental)- [Diviner (diviner)](https://mlflow.org/docs/latest/models.html#diviner-diviner)
- [LangChain (langchain) (Experimental)](https://mlflow.org/docs/latest/models.html#langchain-langchain-experimental)
- [OpenAI (openai) (Experimental)](https://mlflow.org/docs/latest/models.html#openai-openai-experimental)
- [SentenceTransformers (sentence_transformers) (Experimental)](https://mlflow.org/docs/latest/models.html#sentencetransformers-sentence-transformers-experimental)
- [Transformers (transformers) (Experimental)](https://mlflow.org/docs/latest/models.html#transformers-transformers-experimental)

**Comment by skrawcz** [comment]
@bryangalindo we should come up with the Hamilton UX to help guide this. i.e. what's the API we want to expose for Hamilton?

**Comment by bryangalindo** [comment]
> @bryangalindo we should come up with the Hamilton UX to help guide this. i.e. what's the API we want to expose for Hamilton?

Ok let's chat during our sync. Thanks!

**Comment by bryangalindo** [comment]
High-level tasks:

Analysis:
- [ ] Create "hello, world!" version of load_model/log_model to understand mlflow (debug, print stmts, etc).
- [ ] Observe directories/files created from log_model
- [ ] Understand Hamilton driver at a high level (e.g., adapter, builder)
- [ ] Read through files in `examples/materialization`
- [ ] Decide on what reader/writer type makes sense (e.g., .json, MLflowJsonReader/MLflowJsonWriter)
- [ ] Decide on the applicable type (e.g., dataframe, classifiers, regressors)
- [ ] Decide what metadata to save from model (see `hamilton/plugins/mlruns/0/0b9e9b23c3ef443ba638d23e4318b58e/artifacts/model`)
- [ ] Discover kwargs for log_model, load_model

Reader/Writer Implementation:
- [ ] Write reader
- [ ] Write writer
- [ ] Write get metadata function
- [ ] Write unit tests for get metadata function
- [ ] Write unit tests for reader/writer

Materializer Implementation:
- [ ] Write data loader module (see `examples/materialization/data_loaders.py`)
- [ ] Write model_training module (see `examples/materialization/model_training.py`)
- [ ] Write run.py module (see `examples/materialization/run.py`)
- [ ] Write jupyter notebook example (see `examples/materialization/notebook.ipynb`)
- [ ] Write requirements.txt

**Comment by elijahbenizzy** [comment]
Hey @bryangalindo -- a thought on a feature that might be helpful. Here's an outline of what the API should look like -- the data saver/materialization implementatino should support this.

```python
dr = driver.Driver(...)
dr.materialize(
   to.mlflow(
      id="mlflow_save",
      dependencies=["my_cool_model"],
      model_input=source("training_data"),
      model_output=source("predictions"),
   )
)
```

Then the materializer would call `infer_signature` with the `model_input` and `model_output` -- these would be taken from nodes called `training_data` and `predictions`. The DAG would look like:

```my_cool_model -> mlflow_save
training_data -> mlflow_save
predictions -> mlflow_save
```

and possibly more connections. Does this make sense? This is all supported btw -- materializers can take in `source`/`value` type parameters -- if they take in one that isn't it, they'll just resolve to a `value`.

**Comment by zilto** [comment]
Closed in favor of #945

**Pull request closed without merging**
