### PR TITLE
Automate Article Collection and README Updates from Blog Source

### PR DESCRIPTION
**Pull request by sikehish**
This pull request introduces a script for fetching articles from a specified URL(https://blog.dagworks.io/archive), processing the data, and updating the README file with the fetched articles. It addresses issue #1046.

## Changes
- Added a script to fetch articles using Selenium and BeautifulSoup.
- Implemented a function to get a cutoff date from user input.
- Included functionality to update a README file with newly fetched articles.
- Added error handling for date input.
- Included a requirements file for dependencies.

## How I tested this
- Verified that the script correctly fetches articles from the specified URL and logs the output.
- Tested the cutoff date input to ensure it correctly formats and validates the date.
- Confirmed that the README file updates with the new articles correctly and maintains the existing content.

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by skrawcz** [comment]
Awesome, looking forward to trying this tomorrow / Monday!

Otherwise one request -- could you include a "print to standard out" option please?

**Comment by sikehish** [comment]
> Awesome, looking forward to trying this tomorrow / Monday!
> 
> Otherwise one request -- could you include a "print to standard out" option please?
Hi @skrawcz. I've added that option. I've also added a docstring in the python script file so that it would be easier for the users to get started with it.

**Review by skrawcz — APPROVED** [review]

**Comment by skrawcz** [comment]
@sikehish you need to:

1. squash these changes down to a single commit (this will make rebasing simpler)
2. rebase.

Then I can merge this. Otherwise tested locally and it works, thank you!

**Comment by sikehish** [comment]
I tried squashing and rebasing all commits...Is this alright?
I've created a backup branch where I've cherry picked all the commits relevant to this PR(the 6-7 commits relevant to the issue). I can create another PR from the other branch and close this if this looks messed up.

**Comment by skrawcz** [comment]
Thanks @sikehish !

**Pull request merged**
