### PR TITLE
Multiple Usability Improvements

### PR DESCRIPTION
**Pull request by elijahbenizzy**
Fixes:
- [ ] parameterize + Parallel
- [ ] Adds documentation to `Variable` object

We weren't copying over the node source. This is a quick fix, but the better, longer-term fix is to ensure we use `copy_with`. That'll come next, this is just to unblock an OS user.

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by skrawcz** [comment]
Test for this please.

**Comment by elijahbenizzy** [comment]
OK, this PR scope-creeped. Should be testeed/ready now.

**Comment by skrawcz** [comment]
tests are busted?

**Comment by elijahbenizzy** [comment]
> tests are busted?

should be fixed, left in a visualize call

**Review by skrawcz — APPROVED** [review]

**Pull request merged**
